### ISSUE TITLE
First image still shows from collapsed section

### ISSUE THREAD

**Issue by framlingham** [mariusbancila/memefulcomments#10]
After collapsing a method with two images in its internals, the first image still shows, with its top left aligned with the [...].
![Capture showing image from collapsed section](https://user-images.githubusercontent.com/12707910/54256631-68685100-45a8-11e9-9cac-4facd4c8899c.PNG)

Otherwise, I love your extension! I really appreciate the ability to view images inline with source code.

**Comment by mariusbancila** [comment]
Yes, this is a bug that occurs because the collapsed line contains the entire text of the block, which, of course, contains image tags.
