### ISSUE TITLE
 Culture specific parsing of scale property

### ISSUE THREAD

**Issue by cbaekdorf** [mariusbancila/memefulcomments#2]
The scale property is parsed using the culture specific settings, so on my machine (culture da-DK) I have to use scale="0,5" (comma), but on a en-US machine it has to be scale="0.5" (dot). This is not practical when codes is used on machines with different cultures, it should use culture invariant parsing (always 0.5).

**Comment by mariusbancila** [comment]
I changed the parsing to use invariant culture. This is available in the new version 1.2.
