### ISSUE TITLE
Support for Data URIs

### ISSUE THREAD

**Issue by buddde** [mariusbancila/memefulcomments#3]
Hi,

I like your VS Extension, it's great.

I don't have access to the internet on my dev-machine, so it would be great if you support "css like data uris", that way I could include the image in the source code.

Example (taken from [here](https://css-tricks.com/examples/DataURIs/)):

`/// <image url="data:image/gif;base64,R0lGODlhEAAQAMQAAORHHOVSKudfOulrSOp3WOyDZu6QdvCchPGolfO0o/XBs/fNwfjZ0frl3/zy7////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAkAABAALAAAAAAQABAAAAVVICSOZGlCQAosJ6mu7fiyZeKqNKToQGDsM8hBADgUXoGAiqhSvp5QAnQKGIgUhwFUYLCVDFCrKUE1lBavAViFIDlTImbKC5Gm2hB0SlBCBMQiB0UjIQA7" scale="1" />`

**Comment by mariusbancila** [comment]
Thanks for trying the extension.

The idea sounds interesting, although I don't see it's practicality. It could work for very small images, but the base64 encoding of a 20KB picture would take lots of space in the document. You sure you want that?

Why can't you just keep the image on your disk and refer to it? The extension is able to load local files perfectly fine, both using absolute paths and relative one (relative to the document).

**Comment by mariusbancila** [comment]
Version 1.4 has support for VS variables $(SolutionDir) and $(ProjectDir). I suggest you keep images on disk rather than embedded in the image URL.

As I expect this need to be very rare, I don't see a reason to take the effort to implement it.
